<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Stuart Leeds" />

<meta name="date" content="2021-01-12" />

<title>Using the lessR package to investigate wellbeing data</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/journal.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>




<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">(Soc + Occ)Psych/R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    About
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./index.html">Welcome</a>
    </li>
    <li>
      <a href="./index_qual.html">Qualifications</a>
    </li>
    <li>
      <a href="./index_employ.html">Employment</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    500's
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./500_index_soc.html">Social Psychology</a>
    </li>
    <li>
      <a href="./500_index_occ.html">Occupational Psychology</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./project_index_soc.html">Social Psychology</a>
    </li>
    <li>
      <a href="./project_index_occ.html">Occupational Psychology</a>
    </li>
    <li>
      <a href="./project_index_r.html">R - Items of Interest</a>
    </li>
    <li>
      <a href="./project_index_external.html">External Research</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Contact
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mailto:sleeds40@gmail.com">Email</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:sleeds40@gmail.com">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/sleeds50/my_website">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/stuart-leeds2020/">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Using the <code>lessR</code> package to investigate wellbeing data</h1>
<h4 class="author">Stuart Leeds</h4>
<h4 class="date">01/12/2021</h4>

</div>


<p><br></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Employee wellbeing is a concern in occupational psychology. Negative antecedents such as toxic work environments, poor organisational climate, bullying, amount and type of working hours among many others <span class="citation">(<a href="#ref-colliganWorkplaceStressEtiology2006" role="doc-biblioref">Colligan &amp; Higgins, 2006</a>)</span>, increase employee stress. The addition of the Covid-19 pandemic brings new stressors, such as changing working practices by working from home or being on furlough, which have helped contribute to what has become known as <a href="https://www.theguardian.com/money/2021/nov/01/the-great-resignation-almost-one-in-four-workers-planning-job-change">“The Great Resignation” (TGR)</a>.</p>
<p>It would seem that the pandemic has allowed some people to re-evaluate their lives and working practices, thereby, looking after their own wellbeing by doing what is best for them. Though these might be troubling times as far as some employees or organisations are concerned, some recruitment writers see suitable benefits for how TGR can potentially <a href="https://www.reed.co.uk/career-advice/the-great-resignation-and-what-it-means-for-your-career/">benefit your career</a> and consequently increase wellbeing.</p>
<p>However, this is not an essay or report on wellbeing in the workplace. The subject is far too deep and complicated to go into here in any great detail, but the introduction sets the scene.</p>
<p>The idea here is to investigate the relationships between wellbeing and working hours using the <code>lessr</code> package <span class="citation">(<a href="#ref-R-lessR" role="doc-biblioref">Gerbing et al., 2022</a>)</span> which I have recently found to be very useful.</p>
</div>
<div id="the-data" class="section level1">
<h1>The Data</h1>
<p>The wellbeing data are included in the <code>UsingR</code> package <span class="citation">(<a href="#ref-R-UsingR" role="doc-biblioref">Verzani, 2022</a>)</span> and originally used <a href="http://prcweb.co.uk/lab/what-makes-us-happy/">here</a>, where you can see interactive correlations with wellbeing and variables of your choice. There are also links to the data origin at <a href="http://www.nationalaccountsofwellbeing.org/">The National Accounts of Well-being</a> and category data from <a href="https://www.gapminder.org/data/">Gapminder</a>, where you can also download other data from the <em>Gapminder</em> database in CSV or XLSX formats.</p>
<p>The wellbeing data consists of <span class="math inline">\(22\)</span> observations (European countries):</p>
<blockquote>
<p>Austria, Belgium, Bulgaria, Cyprus, Denmark, Estonia, Finland, France, Germany, Hungary, Ireland, Netherlands, Norway, Poland, Portugal, Slovakia, Slovenia, Spain, Sweden, Switzerland, Ukraine, United Kingdom</p>
</blockquote>
<p>and <span class="math inline">\(11\)</span> additional variables:</p>
<blockquote>
<p>Well.being, GDP, Equality, Food.consumption, Alcohol.consumption, Energy.consumption, Family, Working.hours, Work.income, Health.spending, Military.spending</p>
</blockquote>
<p>The data require minimal cleaning, so in this case only the necessary columns are selected with <code>d[]</code> function; and the Well.being column sorted with the <code>Sort()</code> function in <code>lessR</code> (all code for this document can be found in the <a href="#Appendix">Appendix</a>). For the purposes of using <code>lessR</code>, the <code>UsingR::wellbeing</code> data frame was saved as an <code>.xlsx</code> file with <code>Write()</code> and re-imported with <code>Read()</code> into the variable <code>d</code> (you might not have to do this - I could not get the original data to be manipulated with <code>lessR</code> functions).</p>
</div>
<div id="the-analysis" class="section level1">
<h1>The Analysis</h1>
<p>Table 1 shows the top five European countries with the highest wellbeing (Denmark: 5.93), and the bottom five with the lowest wellbeing (Ukraine: 4.39). There’s not much difference between the highest and lowest positions (1.54).</p>
<table class="kable_wrapper lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="padding-bottom:0; padding-left:3px;padding-right:3px;text-align: left; " colspan="1">
<div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
Highest Wellbeing
</div>
</th>
<th style="padding-bottom:0; padding-left:3px;padding-right:3px;text-align: left; " colspan="1">
<div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
Lowest Wellbeing
</div>
</th>
</tr>
</thead>
<caption>
<b>Table 1.</b><br><i>European Countries with Highest &amp; Lowest Wellbeing</i>
</caption>
<tbody>
<tr>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:right;">
Well.being
</th>
<th style="text-align:right;">
Working.hours
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Denmark
</td>
<td style="text-align:right;">
5.93
</td>
<td style="text-align:right;">
30.27
</td>
</tr>
<tr>
<td style="text-align:left;">
Norway
</td>
<td style="text-align:right;">
5.69
</td>
<td style="text-align:right;">
27.08
</td>
</tr>
<tr>
<td style="text-align:left;">
Switzerland
</td>
<td style="text-align:right;">
5.66
</td>
<td style="text-align:right;">
31.87
</td>
</tr>
<tr>
<td style="text-align:left;">
Ireland
</td>
<td style="text-align:right;">
5.44
</td>
<td style="text-align:right;">
31.54
</td>
</tr>
<tr>
<td style="text-align:left;">
Sweden
</td>
<td style="text-align:right;">
5.44
</td>
<td style="text-align:right;">
30.30
</td>
</tr>
</tbody>
</table>
</td>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:right;">
Well.being
</th>
<th style="text-align:right;">
Working.hours
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Estonia
</td>
<td style="text-align:right;">
4.80
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Hungary
</td>
<td style="text-align:right;">
4.74
</td>
<td style="text-align:right;">
38.25
</td>
</tr>
<tr>
<td style="text-align:left;">
Bulgaria
</td>
<td style="text-align:right;">
4.59
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Slovakia
</td>
<td style="text-align:right;">
4.57
</td>
<td style="text-align:right;">
33.63
</td>
</tr>
<tr>
<td style="text-align:left;">
Ukraine
</td>
<td style="text-align:right;">
4.39
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Working.hours are the average working hours per week per person
</td>
</tr>
</tfoot>
</table>
<p><br />
</p>
<p>Not all functions from <code>lessr</code> are necessary for this project. So aside from the “tidying” functions used above, the additional functions of interest are <code>Regression()</code> and <code>regPlot()</code>.</p>
<p>The <code>Regression()</code> function is really useful. As the name <code>lessR</code> suggests, less <span class="math inline">\(R\)</span> and more output. We want to explore the relationship between wellbeing (<em>Intercept</em>) and the average working hours per week per person (<em>predictor</em>). The output for <code>Regression()</code> includes everything you need (and more), all of which can be presented separately if assigned to its own variable, such as:</p>
<p><br />
</p>
<ol style="list-style-type: decimal">
<li>The regression estimate:</li>
</ol>
<pre><code>##                Estimate    Std Err  t-value  p-value   Lower 95%   Upper 95%
##   (Intercept)      7.08       0.83    8.571    0.000        5.32        8.84
## Working.hours     -0.06       0.03   -2.279    0.038       -0.11       -0.00</code></pre>
<p><br />
</p>
<ol start="2" style="list-style-type: decimal">
<li>The Anova:</li>
</ol>
<pre><code>##                 df    Sum Sq   Mean Sq   F-value   p-value
## Model            1      0.58      0.58      5.20     0.038
## Residuals       15      1.68      0.11
## Well.being      16      2.27      0.14</code></pre>
<p><br />
</p>
<ol start="3" style="list-style-type: decimal">
<li>The adjusted R-squared value is <span class="math inline">\((R^2_adj = 0.2077)\)</span>.</li>
</ol>
<p><br />
</p>
<p>The statistical information is reported as follows:</p>
<blockquote>
<p>A simple linear regression was carried out to test if Working Hours significantly predicted Wellbeing. The results of the regression indicated that the model explained 20.77% of the variance and that the model was significant, <span class="math inline">\(F\)</span>(1, 15) <span class="math inline">\(=\)</span> 5.2, <span class="math inline">\(p=\)</span> 0.038. It was found that Working Hours significantly predicted Wellbeing (<span class="math inline">\(B_1=\)</span> -0.06, <span class="math inline">\(p=\)</span> 0.038).<br />
The final predictive model is: proportion of Wellbeing <span class="math inline">\(=\)</span> 7.08 + (-0.06 <span class="math inline">\(\times\)</span> Working Hours)</p>
</blockquote>
</div>
<div id="plots" class="section level1">
<h1>Plots</h1>
<p>Three plots for visualising the regression and the assumptions are also produced (automatically in the <code>Regression()</code> function, or separately using <code>regPlot()</code>, as here:)</p>
<p><strong>Figure 1.</strong><br />
<em>Scatterplot showing regression line, prediction and confidence intervals:</em></p>
<p><img src="lessR_wellbeing_files/figure-html/plot1-1.png" width="672" style="display: block; margin: auto;" /><br />
</p>
<p><strong>Figure 2.</strong><br />
<em>Bar/density plot for distribution of residuals</em></p>
<p><img src="lessR_wellbeing_files/figure-html/plot2-1.png" width="672" style="display: block; margin: auto;" /><br />
</p>
<p><strong>Figure 3.</strong><br />
<em>Scatterplot for residuals vs. fitted values</em></p>
<p><img src="lessR_wellbeing_files/figure-html/plot3-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="additional-output" class="section level1">
<h1>Additional Output</h1>
<p>Additional analyses of interest in the <code>Regression()</code> output are the correlation matrix, which shows a negative moderate relationship between wellbeing and working hours <span class="math inline">\((r= -0.51)\)</span>:</p>
<p><br />
</p>
<ol style="list-style-type: decimal">
<li>RELATIONS AMONG THE VARIABLES:</li>
</ol>
<pre><code>##                 Well.being Working.hours
##      Well.being       1.00         -0.51
##   Working.hours      -0.51          1.00</code></pre>
<p><br />
</p>
<ol start="2" style="list-style-type: decimal">
<li>RESIDUALS AND INFLUENCE (Top five showing here)</li>
</ol>
<pre><code>##  [1] &quot;Data, Fitted, Residual, Studentized Residual, Dffits, Cook&#39;s Distance&quot;
##  [2] &quot;   [sorted by Cook&#39;s Distance]&quot;                                       
##  [3] &quot;   [res_rows = 17, out of 17 ]&quot;                                       
##  [4] &quot;--------------------------------------------------------------&quot;       
##  [5] &quot;     Working.hours Well.being fitted resid rstdnt dffits cooks&quot;       
##  [6] &quot;   9         27.55       5.01   5.45 -0.44  -1.49  -0.65  0.20&quot;       
##  [7] &quot;   5         30.27       5.93   5.29  0.64   2.24   0.62  0.15&quot;       
##  [8] &quot;  16         33.63       4.57   5.09 -0.52  -1.72  -0.51  0.12&quot;       
##  [9] &quot;  20         31.87       5.66   5.19  0.47   1.50   0.37  0.06&quot;       
## [10] &quot;   8         30.16       4.88   5.29 -0.41  -1.32  -0.37  0.06&quot;</code></pre>
<p><br />
</p>
<ol start="3" style="list-style-type: decimal">
<li>PREDICTION ERROR</li>
</ol>
<p>Data, Predicted, Standard Error of Forecast, 95% Prediction Intervals [sorted by lower bound of prediction interval] ———————————————-(Top 5 again)</p>
<pre><code>## [1] &quot;     Working.hours Well.being pred   sf pi.lwr pi.upr width&quot;
## [2] &quot;  10         38.25       4.74 4.82 0.38   4.00   5.64  1.64&quot;
## [3] &quot;  14         38.17       4.81 4.82 0.38   4.00   5.64  1.64&quot;
## [4] &quot;  15         33.81       4.89 5.08 0.35   4.33   5.82  1.49&quot;
## [5] &quot;  16         33.63       4.57 5.09 0.35   4.35   5.83  1.49&quot;
## [6] &quot;   7         32.95       5.39 5.13 0.35   4.39   5.87  1.48&quot;</code></pre>
<p><br />
</p>
<blockquote>
<p>Another excellent feature of the <code>Regression()</code> function is the <code>Rmd = "filename"</code> parameter which automatically produces an explanatory and exploratory <code>.Rmd</code> document of the regression analysis that can be edited; and an additional <code>.html</code> document, which for this analysis you can read <a href="./lessr_wellbeing_out.html">here</a>.</p>
</blockquote>
</div>
<div id="further-query" class="section level1">
<h1>Further Query</h1>
<p>Clearly, working more hours in a week reduces wellbeing. We have already seen that the Wellbeing Mean for this data set is <span class="math inline">\(5.1\)</span>. This could be considered as <em>peak</em> wellbeing, so what are the average working hours per week per person needed to maintain that level of wellbeing?</p>
<p>The prediction output suggests a level of wellbeing at <span class="math inline">\(5.13\)</span> <span class="math inline">\((95\%\space CI[4.39, 5.87])\)</span> for <span class="math inline">\(32.95\)</span> (round to <span class="math inline">\(33\)</span>) average hours worked at item <span class="math inline">\(7\)</span>:</p>
<pre><code>## [1] &quot;     Working.hours Well.being pred   sf pi.lwr pi.upr width&quot;
## [2] &quot;   7         32.95       5.39 5.13 0.35   4.39   5.87  1.48&quot;</code></pre>
<p><br />
</p>
<p>This prediction can be confirmed with the regression calculation identified above:</p>
<blockquote>
<p>Wellbeing = 7.08 + (-0.06 <span class="math inline">\(\times\)</span> Working Hours) <span class="math inline">\(\space\therefore\space\)</span> 7.08 + (-0.06 <span class="math inline">\(\times\)</span> 33) <span class="math inline">\(=\)</span> 5.13</p>
</blockquote>
<p>If the preferred working hours to maintain wellbeing at <span class="math inline">\(5.13\)</span> is <span class="math inline">\(33\)</span>, then the question is: would it be more beneficial to work a shorter week with longer hours per day, or a longer week with fewer hours per day? See Table 2 (Calculations converted to time with <code>lubridate</code> <span class="citation">(<a href="#ref-R-lubridate" role="doc-biblioref">Spinu et al., 2021</a>)</span>).</p>
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<b>Table 2.</b><br><i>Speculative Working Week</i>
</caption>
<thead>
<tr>
<th style="text-align:right;">
Days per Week
</th>
<th style="text-align:right;">
Hours per Day
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8H 15M 0S
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
6H 36M 0S
</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<p>Of course there are other options, for example, a three day week at <span class="math inline">\(11\)</span> hours per day, or a six day week at <span class="math inline">\(5\)</span> hours <span class="math inline">\(30\)</span> minutes per day, not intending to dismiss those workers who would do more (or less).</p>
<p>This theory does not account for the four countries that work fewer than <span class="math inline">\(33\)</span> hours per week per person and have a lower than average wellbeing: <em>Belgium, France, Germany</em> and the <em>United Kingdom</em> (See the lower-left quadrant of Figure 1; and Table 3).</p>
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<b>Table 3.</b><br><i>European Countries with Wellbeing &lt; 5.13 and Working Hours &lt; 33</i>
</caption>
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:right;">
Well.being
</th>
<th style="text-align:right;">
Well.being.diff
</th>
<th style="text-align:right;">
Working.hours
</th>
<th style="text-align:right;">
Working.hours.diff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Belgium
</td>
<td style="text-align:right;">
5.04
</td>
<td style="text-align:right;">
-0.09
</td>
<td style="text-align:right;">
30.21
</td>
<td style="text-align:right;">
-2.79
</td>
</tr>
<tr>
<td style="text-align:left;">
France
</td>
<td style="text-align:right;">
4.88
</td>
<td style="text-align:right;">
-0.25
</td>
<td style="text-align:right;">
30.16
</td>
<td style="text-align:right;">
-2.84
</td>
</tr>
<tr>
<td style="text-align:left;">
Germany
</td>
<td style="text-align:right;">
5.01
</td>
<td style="text-align:right;">
-0.12
</td>
<td style="text-align:right;">
27.55
</td>
<td style="text-align:right;">
-5.45
</td>
</tr>
<tr>
<td style="text-align:left;">
United Kingdom
</td>
<td style="text-align:right;">
4.98
</td>
<td style="text-align:right;">
-0.15
</td>
<td style="text-align:right;">
32.09
</td>
<td style="text-align:right;">
-0.91
</td>
</tr>
</tbody>
</table>
<p><br />
</p>
<p>In this group, <em>France</em> has the largest difference in wellbeing <span class="math inline">\((-0.25)\)</span>, a <span class="math inline">\(1/4\)</span> of a point less than average wellbeing. However, all of the wellbeing differences are <em>very</em> small; and the wellbeing scores for each country are within the bounds of the <span class="math inline">\(95\%\space CI[4.39, 5.87]\)</span> of the wellbeing/working hours prediction. The country with the greatest working hours difference is <em>Germany</em> at <span class="math inline">\(-5.45\)</span>, which is <span class="math inline">\(5\)</span> hours <span class="math inline">\(27\)</span> minutes fewer than average. Further research is required to determine the <em>whys</em> and <em>wherefores</em>, which is beyond the scope of this report.</p>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>A very brief introduction to employee wellbeing preceded the purpose of using various functions from the <code>lessR</code> package to explore the relationship between Well.being and Working.hours in <span class="math inline">\(22\)</span> European countries using the <code>UsingR::wellbeing</code> data set. The <code>lessR</code> functions used were <code>Write()</code>, <code>Read()</code>, <code>d[]</code>, <code>Sort()</code>, <code>Regression()</code> and <code>regPlot()</code>. The key <code>Regression()</code> outputs, <em>estimate, ANOVA</em> and <em>adjusted R-squared</em> were presented separately to weave into the text, along with three plots to verify regression assumptions. Additional output for <em>correlation, residuals and influence</em> and <em>prediction error</em> followed. Further query suggested a predicted number of average working hours to maintain average wellbeing, with speculative thought on how a working week could be arranged. Finally, the four countries showing less than wellbeing average and fewer than average working hours were addressed. In general, <code>lessR</code> was found to be an excellent <span class="math inline">\(R\)</span> package to manipulate data with minimal use of <span class="math inline">\(R\)</span> for maximum output.</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-colliganWorkplaceStressEtiology2006" class="csl-entry">
Colligan, T. W., &amp; Higgins, E. M. (2006). Workplace stress: <span>Etiology</span> and consequences. <em>Journal of Workplace Behavioral Health</em>, <em>21</em>(2, 2), 89–97. <a href="https://doi.org/10.1300/J490v21n02_07">https://doi.org/10.1300/J490v21n02_07</a>
</div>
<div id="ref-R-lessR" class="csl-entry">
Gerbing, D., Business, T. S. of, &amp; University, P. S. (2022). <em>lessR: Less code, more results</em>. <a href="https://CRAN.R-project.org/package=lessR">https://CRAN.R-project.org/package=lessR</a>
</div>
<div id="ref-R-lubridate" class="csl-entry">
Spinu, V., Grolemund, G., &amp; Wickham, H. (2021). <em>Lubridate: Make dealing with dates a little easier</em>. <a href="https://CRAN.R-project.org/package=lubridate">https://CRAN.R-project.org/package=lubridate</a>
</div>
<div id="ref-R-UsingR" class="csl-entry">
Verzani, J. (2022). <em>UsingR: Data sets, etc. For the text "using r for introductory statistics", second edition</em>. <a href="https://CRAN.R-project.org/package=UsingR">https://CRAN.R-project.org/package=UsingR</a>
</div>
</div>
<p><br />
</p>
</div>
<div id="Appendix" class="section level1">
<h1>Appendix: All code for this article</h1>
<pre class="r"><code># Setup
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  results = &quot;hide&quot;,
  fig.align = &quot;center&quot;
)

# Libraries
library(UsingR) # For wellbeing data
library(lessR) # Main package
library(kableExtra) # For tables
library(lubridate) # For date &amp; time functions

# Creation of R package citation file
knitr::write_bib(c(.packages(), &quot;rmarkdown&quot;), &quot;../common/packages.bib&quot;)

# Data loading from UsingR
mydata &lt;- wellbeing

# Write to `lessr` .xlsx format (uncomment - only needs doing once)
# Write(&quot;./data/wellbeing&quot;, format = &quot;Excel&quot;, data = mydata)

# Read data
d &lt;- Read(&quot;./data/wellbeing.xlsx&quot;)</code></pre>
<pre><code>## [with the read.xlsx() function from Schauberger and Walker&#39;s openxlsx package] 
## 
## &gt;&gt;&gt; Suggestions
## To read a csv or Excel file of variable labels, var_labels=TRUE
##    Each row of the file:  Variable Name, Variable Label
## Details about your data, Enter:  details()  for d, or  details(name)
## 
## Data Types
## ------------------------------------------------------------
## character: Non-numeric data values
## double: Numeric data values with decimal digits
## ------------------------------------------------------------
## 
##                Variable                  Missing  Unique 
##                    Name     Type  Values  Values  Values   First and last values
## ------------------------------------------------------------------------------------------
##  1              Country character     22       0      22   Austria ... United Kingdom
##  2           Well.being    double     22       0      21   5.37  5.04  4.59 ... 5.66  4.39  4.98
##  3                  GDP    double     22       0      22   26171.6909118266 ... 28913.0962918089
##  4             Equality    double     21       1      21   70.85  67.03 ... 71.77375  64.03
##  5     Food.consumption    double     22       0      22   3760.36  3674.95 ... 3251.21  3437.22
##  6  Alcohol.consumption    double     22       0      21   13.24  10.77  12.44 ... 11.06  15.6  13.37
##  7   Energy.consumption    double     22       0      22   2076.20046430559 ... 1921.65630197802
##  8               Family    double     22       0      21   1.4054  1.76  1.39 ... 1.43  1.3  1.77
##  9        Working.hours    double     17       5      17   31.8173076923077 ... 32.0903836763822
## 10          Work.income    double     16       6      16   30.4599990844727 ... 27.1000003814697
## 11      Health.spending    double     22       0      22   15.74170456 ... 15.58877599
## 12    Military.spending    double     22       0      22   0.812633138406514 ... 2.35142785961432
## ------------------------------------------------------------------------------------------
## 
## 
## For the column Country, each row of data is unique. Are these values
## a unique ID for each row? To implement, perhaps re-read a worksheet or text
## file with the following setting added to your Read statement: row_names=1</code></pre>
<pre class="r"><code># Select columns of interest
d &lt;- d[, .(&quot;Country&quot;, &quot;Well.being&quot;, &quot;Working.hours&quot;)]

# Sort countries by wellbeing
d_sort &lt;- Sort(d, Well.being, direction = &quot;-&quot;)</code></pre>
<pre><code>## 
## Sort Specification
##   Well.being --&gt;  descending</code></pre>
<pre class="r"><code># Table top/bottom five
wb_tab &lt;- kbl(list(head(d_sort, 5), tail(d_sort, 5)),
  caption = &quot;&lt;b&gt;Table 1.&lt;/b&gt;&lt;br&gt;&lt;i&gt;European Countries with Highest &amp; Lowest  Wellbeing&lt;/i&gt;&quot;,
  row.names = F, digits = 2
) |&gt;
  kable_classic(full_width = FALSE) |&gt;
  add_header_above(c(
    &quot;Highest Wellbeing&quot;,
    &quot;Lowest Wellbeing&quot;
  ),
  align = &quot;l&quot;
  )

footnote(wb_tab, 
         general = &quot;Working.hours are the average working hours per week per person&quot;)</code></pre>
<table class="kable_wrapper lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
<thead>
<tr>
<th style="padding-bottom:0; padding-left:3px;padding-right:3px;text-align: left; " colspan="1">
<div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
Highest Wellbeing
</div>
</th>
<th style="padding-bottom:0; padding-left:3px;padding-right:3px;text-align: left; " colspan="1">
<div style="border-bottom: 1px solid #111111; margin-bottom: -1px; ">
Lowest Wellbeing
</div>
</th>
</tr>
</thead>
<caption>
<b>Table 1.</b><br><i>European Countries with Highest &amp; Lowest Wellbeing</i>
</caption>
<tbody>
<tr>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:right;">
Well.being
</th>
<th style="text-align:right;">
Working.hours
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Denmark
</td>
<td style="text-align:right;">
5.93
</td>
<td style="text-align:right;">
30.27
</td>
</tr>
<tr>
<td style="text-align:left;">
Norway
</td>
<td style="text-align:right;">
5.69
</td>
<td style="text-align:right;">
27.08
</td>
</tr>
<tr>
<td style="text-align:left;">
Switzerland
</td>
<td style="text-align:right;">
5.66
</td>
<td style="text-align:right;">
31.87
</td>
</tr>
<tr>
<td style="text-align:left;">
Ireland
</td>
<td style="text-align:right;">
5.44
</td>
<td style="text-align:right;">
31.54
</td>
</tr>
<tr>
<td style="text-align:left;">
Sweden
</td>
<td style="text-align:right;">
5.44
</td>
<td style="text-align:right;">
30.30
</td>
</tr>
</tbody>
</table>
</td>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:right;">
Well.being
</th>
<th style="text-align:right;">
Working.hours
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Estonia
</td>
<td style="text-align:right;">
4.80
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Hungary
</td>
<td style="text-align:right;">
4.74
</td>
<td style="text-align:right;">
38.25
</td>
</tr>
<tr>
<td style="text-align:left;">
Bulgaria
</td>
<td style="text-align:right;">
4.59
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Slovakia
</td>
<td style="text-align:right;">
4.57
</td>
<td style="text-align:right;">
33.63
</td>
</tr>
<tr>
<td style="text-align:left;">
Ukraine
</td>
<td style="text-align:right;">
4.39
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Working.hours are the average working hours per week per person
</td>
</tr>
</tfoot>
</table>
<pre class="r"><code># The `Regression` function
r &lt;- Regression(Well.being ~ Working.hours,
  digits_d = 2,
  # Rmd = &quot;lessr_wellbeing_out&quot;, # uncomment for Rmd, change name to suit
  graphics = FALSE # Replace with TRUE for three plots:
  # (1: Regression, 2: Distribution, 3: Fitted Values)
)

r</code></pre>
<pre><code>## &gt;&gt;&gt; Suggestion
## # Create an R markdown file for interpretative output with  Rmd = &quot;file_name&quot;
## Regression(my_formula=Well.being ~ Working.hours, digits_d=2, graphics=FALSE, Rmd=&quot;eg&quot;)  
## 
##   BACKGROUND 
## 
## Data Frame:  d 
##  
## Response Variable: Well.being 
## Predictor Variable: Working.hours 
##  
## Number of cases (rows) of data:  22 
## Number of cases retained for analysis:  17 
## 
##   BASIC ANALYSIS 
## 
##                Estimate    Std Err  t-value  p-value   Lower 95%   Upper 95% 
##   (Intercept)      7.08       0.83    8.571    0.000        5.32        8.84 
## Working.hours     -0.06       0.03   -2.279    0.038       -0.11       -0.00 
## 
## Standard deviation of Well.being: 0.40 
##  
## Standard deviation of residuals:  0.33 for 15 degrees of freedom 
## 95% range of residual variation:  1.43 = 2 * (2.131 * 0.33) 
##  
## R-squared:  0.257    Adjusted R-squared:  0.208    PRESS R-squared:  0.102 
## 
## Null hypothesis of all 0 population slope coefficients:
##   F-statistic: 5.195     df: 1 and 15     p-value:  0.038 
## 
##                 df    Sum Sq   Mean Sq   F-value   p-value 
## Model            1      0.58      0.58      5.20     0.038 
## Residuals       15      1.68      0.11 
## Well.being      16      2.27      0.14 
## 
##   K-FOLD CROSS-VALIDATION 
## 
##   RELATIONS AMONG THE VARIABLES 
## 
##                 Well.being Working.hours 
##      Well.being       1.00         -0.51 
##   Working.hours      -0.51          1.00 
## 
##   RESIDUALS AND INFLUENCE 
## 
## Data, Fitted, Residual, Studentized Residual, Dffits, Cook&#39;s Distance 
##    [sorted by Cook&#39;s Distance] 
##    [res_rows = 17, out of 17 ] 
## -------------------------------------------------------------- 
##      Working.hours Well.being fitted resid rstdnt dffits cooks 
##    9         27.55       5.01   5.45 -0.44  -1.49  -0.65  0.20 
##    5         30.27       5.93   5.29  0.64   2.24   0.62  0.15 
##   16         33.63       4.57   5.09 -0.52  -1.72  -0.51  0.12 
##   20         31.87       5.66   5.19  0.47   1.50   0.37  0.06 
##    8         30.16       4.88   5.29 -0.41  -1.32  -0.37  0.06 
##   13         27.08       5.69   5.48  0.21   0.69   0.33  0.06 
##   12         26.75       5.31   5.50 -0.19  -0.61  -0.31  0.05 
##    7         32.95       5.39   5.13  0.26   0.80   0.22  0.02 
##    2         30.21       5.04   5.29 -0.25  -0.77  -0.21  0.02 
##   10         38.25       4.74   4.82 -0.08  -0.26  -0.18  0.02 
##   15         33.81       4.89   5.08 -0.19  -0.58  -0.18  0.02 
##   11         31.54       5.44   5.21  0.23   0.69   0.17  0.02 
##   22         32.09       4.98   5.18 -0.20  -0.60  -0.15  0.01 
##    1         31.82       5.37   5.20  0.17   0.52   0.13  0.01 
##   19         30.30       5.44   5.29  0.15   0.46   0.13  0.01 
##   18         31.82       5.34   5.20  0.14   0.43   0.11  0.01 
##   14         38.17       4.81   4.82 -0.01  -0.04  -0.02  0.00 
## 
##   PREDICTION ERROR 
## 
## Data, Predicted, Standard Error of Forecast, 
## 95% Prediction Intervals 
##    [sorted by lower bound of prediction interval] 
##  ---------------------------------------------- 
## 
##      Working.hours Well.being pred   sf pi.lwr pi.upr width 
##   10         38.25       4.74 4.82 0.38   4.00   5.64  1.64 
##   14         38.17       4.81 4.82 0.38   4.00   5.64  1.64 
##   15         33.81       4.89 5.08 0.35   4.33   5.82  1.49 
##   16         33.63       4.57 5.09 0.35   4.35   5.83  1.49 
##    7         32.95       5.39 5.13 0.35   4.39   5.87  1.48 
##   22         32.09       4.98 5.18 0.34   4.45   5.91  1.47 
##   20         31.87       5.66 5.19 0.34   4.46   5.93  1.47 
##   18         31.82       5.34 5.20 0.34   4.46   5.93  1.47 
##    1         31.82       5.37 5.20 0.34   4.46   5.93  1.47 
##   11         31.54       5.44 5.21 0.34   4.48   5.95  1.47 
##   19         30.30       5.44 5.29 0.35   4.55   6.02  1.48 
##    5         30.27       5.93 5.29 0.35   4.55   6.03  1.48 
##    2         30.21       5.04 5.29 0.35   4.55   6.03  1.48 
##    8         30.16       4.88 5.29 0.35   4.56   6.03  1.48 
##    9         27.55       5.01 5.45 0.36   4.68   6.22  1.54 
##   13         27.08       5.69 5.48 0.36   4.70   6.25  1.55 
##   12         26.75       5.31 5.50 0.37   4.71   6.28  1.57</code></pre>
<pre class="r"><code># The estimates output
r$out_estimates</code></pre>
<pre><code>##                Estimate    Std Err  t-value  p-value   Lower 95%   Upper 95%
##   (Intercept)      7.08       0.83    8.571    0.000        5.32        8.84
## Working.hours     -0.06       0.03   -2.279    0.038       -0.11       -0.00</code></pre>
<pre class="r"><code># The ANOVA output
r$out_anova</code></pre>
<pre><code>##                 df    Sum Sq   Mean Sq   F-value   p-value
## Model            1      0.58      0.58      5.20     0.038
## Residuals       15      1.68      0.11
## Well.being      16      2.27      0.14</code></pre>
<pre class="r"><code># The regression plot
regPlot(r, 1, res_rows = &quot;all&quot;) # Max rows = 20, use `res_rows=&#39;all&#39;` for all rows</code></pre>
<p><img src="lessR_wellbeing_files/figure-html/unnamed-chunk-1-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># The residual barplot
regPlot(r, 2, res_rows = &quot;all&quot;) # Max rows = 20, use `res_rows=&#39;all&#39;` for all rows</code></pre>
<p><img src="lessR_wellbeing_files/figure-html/unnamed-chunk-1-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># The residual scatterplot
regPlot(r, 3, res_rows = &quot;all&quot;) # Max rows = 20, use `res_rows=&#39;all&#39;` for all rows</code></pre>
<p><img src="lessR_wellbeing_files/figure-html/unnamed-chunk-1-3.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># The correlation matrix
r$out_cor</code></pre>
<pre><code>##                 Well.being Working.hours
##      Well.being       1.00         -0.51
##   Working.hours      -0.51          1.00</code></pre>
<pre class="r"><code># The residuals output
head(r$out_residuals, 10)</code></pre>
<pre><code>##  [1] &quot;Data, Fitted, Residual, Studentized Residual, Dffits, Cook&#39;s Distance&quot;
##  [2] &quot;   [sorted by Cook&#39;s Distance]&quot;                                       
##  [3] &quot;   [res_rows = 17, out of 17 ]&quot;                                       
##  [4] &quot;--------------------------------------------------------------&quot;       
##  [5] &quot;     Working.hours Well.being fitted resid rstdnt dffits cooks&quot;       
##  [6] &quot;   9         27.55       5.01   5.45 -0.44  -1.49  -0.65  0.20&quot;       
##  [7] &quot;   5         30.27       5.93   5.29  0.64   2.24   0.62  0.15&quot;       
##  [8] &quot;  16         33.63       4.57   5.09 -0.52  -1.72  -0.51  0.12&quot;       
##  [9] &quot;  20         31.87       5.66   5.19  0.47   1.50   0.37  0.06&quot;       
## [10] &quot;   8         30.16       4.88   5.29 -0.41  -1.32  -0.37  0.06&quot;</code></pre>
<pre class="r"><code># The prediction output
head(r$out_predict)</code></pre>
<pre><code>## [1] &quot;     Working.hours Well.being pred   sf pi.lwr pi.upr width&quot;
## [2] &quot;  10         38.25       4.74 4.82 0.38   4.00   5.64  1.64&quot;
## [3] &quot;  14         38.17       4.81 4.82 0.38   4.00   5.64  1.64&quot;
## [4] &quot;  15         33.81       4.89 5.08 0.35   4.33   5.82  1.49&quot;
## [5] &quot;  16         33.63       4.57 5.09 0.35   4.35   5.83  1.49&quot;
## [6] &quot;   7         32.95       5.39 5.13 0.35   4.39   5.87  1.48&quot;</code></pre>
<pre class="r"><code># The prediction output for 5.13 wellbeing
r$out_predict[c(1, 6)]</code></pre>
<pre><code>## [1] &quot;     Working.hours Well.being pred   sf pi.lwr pi.upr width&quot;
## [2] &quot;   7         32.95       5.39 5.13 0.35   4.39   5.87  1.48&quot;</code></pre>
<pre class="r"><code># The data frame for speculative working week
time_table &lt;- data.frame(
  &quot;Days&quot; = c(4, 5),
  &quot;Hours&quot; = c(
      seconds_to_period(33 / 4 * 3600), seconds_to_period(33 / 5 * 3600))
)

# The table for speculative working week
kbl(time_table,
  caption = &quot;&lt;b&gt;Table 2.&lt;/b&gt;&lt;br&gt;&lt;i&gt;Speculative Working Week&lt;/i&gt;&quot;,
  row.names = FALSE, 
  col.names = c(&quot;Days per Week&quot;, &quot;Hours per Day&quot;)
) |&gt;
  kable_classic(full_width = FALSE)</code></pre>
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<b>Table 2.</b><br><i>Speculative Working Week</i>
</caption>
<thead>
<tr>
<th style="text-align:right;">
Days per Week
</th>
<th style="text-align:right;">
Hours per Day
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8H 15M 0S
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
6H 36M 0S
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Find countries with wellbeing &lt; 5.13 and working hours &lt; 33
ifelse(d$Well.being &lt; 5.13 &amp; d$Working.hours &lt; 33, d$Country, NA)</code></pre>
<pre><code>##  [1] NA               &quot;Belgium&quot;        NA               NA              
##  [5] NA               NA               NA               &quot;France&quot;        
##  [9] &quot;Germany&quot;        NA               NA               NA              
## [13] NA               NA               NA               NA              
## [17] NA               NA               NA               NA              
## [21] NA               &quot;United Kingdom&quot;</code></pre>
<pre class="r"><code># Data frame for countries with wellbeing &lt; 5.13 and working hours &lt; 33
less_well &lt;- data.frame(
  Country = c(d$Country[2], d$Country[8], 
              d$Country[9], d$Country[22]),
  Well.being = c(d$Well.being[2], d$Well.being[8], 
                 d$Well.being[9], d$Well.being[22]),
  Well.being.diff = c(d$Well.being[2] - 5.13, d$Well.being[8] - 5.13, 
                      d$Well.being[9] - 5.13, d$Well.being[22] - 5.13),
  Working.hours = c(d$Working.hours[2], d$Working.hours[8], 
                    d$Working.hours[9], d$Working.hours[22]),
  Working.hours.diff = c(d$Working.hours[2] - 33, d$Working.hours[8] - 33, 
                         d$Working.hours[9] - 33, d$Working.hours[22] - 33)
)

# Table for countries with wellbeing &lt; 5.13 and working hours &lt; 33
kbl(less_well,
  caption = &quot;&lt;b&gt;Table 3.&lt;/b&gt;&lt;br&gt;&lt;i&gt;European Countries with Wellbeing &lt; 5.13 and Working Hours &lt; 33&lt;/i&gt;&quot;,
  row.names = F, digits = 2
) |&gt;
  kable_classic(full_width = FALSE)</code></pre>
<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<b>Table 3.</b><br><i>European Countries with Wellbeing &lt; 5.13 and Working Hours &lt; 33</i>
</caption>
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:right;">
Well.being
</th>
<th style="text-align:right;">
Well.being.diff
</th>
<th style="text-align:right;">
Working.hours
</th>
<th style="text-align:right;">
Working.hours.diff
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Belgium
</td>
<td style="text-align:right;">
5.04
</td>
<td style="text-align:right;">
-0.09
</td>
<td style="text-align:right;">
30.21
</td>
<td style="text-align:right;">
-2.79
</td>
</tr>
<tr>
<td style="text-align:left;">
France
</td>
<td style="text-align:right;">
4.88
</td>
<td style="text-align:right;">
-0.25
</td>
<td style="text-align:right;">
30.16
</td>
<td style="text-align:right;">
-2.84
</td>
</tr>
<tr>
<td style="text-align:left;">
Germany
</td>
<td style="text-align:right;">
5.01
</td>
<td style="text-align:right;">
-0.12
</td>
<td style="text-align:right;">
27.55
</td>
<td style="text-align:right;">
-5.45
</td>
</tr>
<tr>
<td style="text-align:left;">
United Kingdom
</td>
<td style="text-align:right;">
4.98
</td>
<td style="text-align:right;">
-0.15
</td>
<td style="text-align:right;">
32.09
</td>
<td style="text-align:right;">
-0.91
</td>
</tr>
</tbody>
</table>
</div>




 <!-- remove Html comment bars below when enough content --> 

 <!-- <p>Copyright &copy; 2021 S.M.Leeds. All rights reserved.</p> --> 



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
